name: Build and deploy Vite React app to Azure Web App - leadgenwingman

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest commit in the main branch
      - uses: actions/checkout@v4

      # Set up Node.js version 20.x
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies and build the Vite React app
      - name: Install dependencies and build
        working-directory: ./lead_generation_agentic_team-ui
        run: |
          npm install
          npm run build

      # Zip the build directory for deployment
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip ./lead_generation_agentic_team-ui/dist/*

      # Upload the zip artifact for use in the deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Unzip the artifact for deployment
      - name: Unzip artifact for deployment
        run: unzip release.zip -d .

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_559a63a9-46fc-488e-93fb-cc50d98696f4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3a13f0b9-bdf9-4ff0-a365-de072ebdbd26 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_f46c5aea-6d78-4485-b558-327eecd54457}}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET_e53775ff-b455-414e-b35f-d4e4b88858ab }} 

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'leadgenwingman'  # Your Azure Web App name
          slot-name: 'Production'     # Use 'default' if no slot is configured
          package: './lead_generation_agentic_team-ui/dist/'
